name: Build & Deploy site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build, Test and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          CI: true
          NODE_ENV: production
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # The branch the action should deploy from.
          BASE_BRANCH: master
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: src
